### ISSUE TITLE
Switching the language forgets url parameters

### ISSUE THREAD

**Issue by FrancMeles** [pceuropa/yii2-language-selection-widget#1]
Widget generates urls for languages withoud current parameters. Maybe you should consider changing line in allFlag function to sth like this:
$a = Html::a ($img , \yii\helpers\Url::current([$this->languageParam => $key]) );
Thanks for nice and clean widget.

**Comment by pceuropa** [comment]
thank you, I'll consider this change.

Url::current added in 1.1.1
